name = "ReDiverse"
uuid = "3955ef1e-a3c5-4a6e-afd8-9ba03e5c0c85"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com>"]
version = "0.2.0"		# QC

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
